# EPCIS Knowledge Graph Configuration

# Database settings
database_path = "./data"
server_port = 8080

# Logging level: trace, debug, info, warn, error
log_level = "info"

# Ontology paths (relative to project root or absolute paths)
ontology_paths = [
    "ontologies/epcis2.ttl",
    "ontologies/cbv.ttl"
]

# Reasoning settings
[reasoning]
default_profile = "el"  # OWL 2 profile: el, ql, rl
enable_inference = true
max_inference_time = 30  # seconds

# SPARQL settings
[sparql]
max_query_time = 60  # seconds
max_results = 1000  # maximum number of results to return
enable_updates = true

# Server settings
[server]
enable_cors = true
cors_origins = ["*"]
request_timeout = 30  # seconds

# Persistence settings
[persistence]
auto_save = true
save_interval = 300  # seconds (5 minutes)
backup_on_startup = true