# EPCIS Knowledge Graph Configuration

[database]
path = "./data"
# max_size_mb = 1024

[server]
port = 8080
host = "127.0.0.1"

[logging]
level = "info"
# format = "json"

[ontologies]
# Paths to ontology files (Turtle format)
epcis_path = "ontologies/epcis.ttl"
cbv_path = "ontologies/cbv.ttl"

[reasoning]
enabled = true
profile = "RL"  # EL, QL, or RL

[performance]
query_timeout_ms = 30000
max_concurrent_queries = 100